//-----------------------------------------------------------------------------
// AUTOGENERATED: Compiled Verilog Defines List
//
// Copyright (C) 2026, SoC Labs (www.soclabs.org)
//-----------------------------------------------------------------------------
// Regenerated by the arch_tech makefile from NANOSOC_DEFINES. The committed copy
// is the QuickStart baseline: no DMA, so no DMAC_0_PL230.
//-----------------------------------------------------------------------------

`define FAST_SIM
`define RAM_PRELOAD
